creation of SearchPreferences class to store user's preferences
CHARLONCyril/2D-Library pull request #17
Opened 2019-06-26 20:16 UTC by CHARLONCyril

Creation of an object that stores user preferences

2019-06-27 10:08 UTC, oliviercailloux requested changes
Facultatif : Rendre `SearchPrefrences` immuable. (Voir comment faire pour permettre le parsing sans permettre aux clients d’accéder aux setters.) Ou ajouter une issue pour laisser cette tâche pour plus tard.

2019-06-27 19:51 UTC, CHARLONCyril commented
We reworked SearchPreferences class for made it immutable.

2019-06-29 10:00 UTC, oliviercailloux approved these changes
Ok vu l’urgence, et vu que j’ai oublié d’insister sur ce point précédemment, mais il aurait fallu également un test unitaire qui vérifie la lecture et l’écriture d’une SearchPreferences. Voyez si vous avez le temps d’y travailler.

2019-06-29 10:02 UTC, oliviercailloux commented
Ah ok j’avais demandé ceci dans une autre PR.

2019-06-29 10:39 UTC, merged