Write prefs
CHARLONCyril/2D-Library pull request #9
Opened 2019-06-03 19:53 UTC by HenryJulienDesgranges

Added the functionnality to save user's preferences in a csv file (write / read).

2019-06-04 10:59 UTC, oliviercailloux requested changes
Utiliser une bibliothèque pour parser le CSV, par exemple uniVocity. (Votre code fonctionne-t-il si une entrée contient une virgule suivie d’un guillemet ?)

Découper systématiquement en méthodes, code trop long et difficile à suivre.

2019-06-04 10:59 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/twod_library/controller/CSVUtils.java
> +			e.printStackTrace();
EXC

2019-06-04 10:59 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/twod_library/view/Window2DLibrary.java
> +					CSVUtils.writeCSVFile("UserPreference.csv", "/src/main/resources/controller/", csvFile);
Code difficile à lire. Découper en méthodes.

2019-06-04 10:59 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/twod_library/view/Window2DLibrary.java
>  					ex.printStackTrace();
EXC

2019-06-04 10:59 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/twod_library/view/Window2DLibrary.java
> +	private HashMap<String, Map<String, String>> UserSettings = CSVUtils.read("/src/main/resources/controller/",
BP Resources

2019-06-20 18:25 UTC, oliviercailloux requested changes
Enlevez tous les try-catch inutiles.
Je ne comprends pas comment vous envisagez le format CSV, mais en tous cas, il y a visiblement un problème. Voyez des exemples sur internet.

2019-06-20 18:25 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/twod_library/controller/CSVUtils.java
> +		writer.writeRowsAndClose(content);
Vous ne pouvez pas écrire dans votre class path.

2019-06-20 18:25 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/twod_library/controller/CSVUtils.java
> +	public static HashMap<String, Map<String, String>> parseCSVFile(String fileName) throws URISyntaxException {
Il n’y a pas de raison de s’engager à renvoyer une `HashMap`. `Map` suffit.

2019-06-20 18:25 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/twod_library/controller/CSVUtils.java
> +	 *         representing the value chosen by the user.
vos valeurs sont elles-mêmes des maps. Expliquer ici à quoi cela correspond, en l’état je ne comprends pas.

2019-06-20 18:25 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/twod_library/view/Window2DLibrary.java
>  					updateSVGLibrary();
À éviter : un gros bloc de code embarqué dans un try dans un if dans une méthode imbriquée dans une autre méthode. Utiliser une référence de méthode et découper en sous-méthodes éventuellement.

2019-06-20 18:25 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/twod_library/view/Window2DLibrary.java
> +						Object cle = it.next();
In English, please

2019-06-20 18:25 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/twod_library/view/Window2DLibrary.java
> +						ex1.printStackTrace();
Logique incorrecte. Lancer une exception runtime, t.q. IllegalStateException. Ne pas logger et lancer, pour éviter double traitement.

2019-06-21 08:50 UTC, oliviercailloux requested changes
Comme discuté en séance, j’attends une modification du format du CSV (ligne : un utilisateur, colonnes : les différentes propriétés).

2019-06-24 19:41 UTC, CHARLONCyril commented
We had changed the csv format and we saved it on hard disk

2019-06-25 12:33 UTC, oliviercailloux requested changes
Il convient de fabriquer un objet qui représente les préférences de l’utilisateur, et d’éviter d’utiliser des listes de listes d’objets, ou autres structures tout aussi alambiquées, mais d’utiliser plutôt ces objets représentant ces préférences.

2019-06-25 12:33 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/twod_library/view/Window2DLibrary.java
> +	private List<String[]> UserSettings;
Pourquoi une liste de vecteurs de string ? L’objectif de cette structure est difficile à comprendre, et elle sera difficile à manipuler.

2019-06-25 22:06 UTC, CHARLONCyril commented
We had created objects which represents user's preferences.

2019-06-25 22:12 UTC, CHARLONCyril commented
We created objects to store user's preferences.

2019-06-26 10:07 UTC, oliviercailloux commented
FOCUS. Une tâche à la fois SVP. Créez une autre PR pour l’objet qui permet de conserver les préférences d’un utilisateur. Celle-ci devient extrêmement difficile à évaluer avec toutes ces modifications sur plusieurs aspects.

2019-06-26 19:18 UTC, closed without merging